# Generated by Django 5.0 on 2024-01-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend', models.CharField(max_length=50)),
                ('marka', models.CharField(max_length=50)),
                ('power', models.IntegerField(max_length=4)),
                ('level', models.CharField(max_length=10)),
            ],
        ),
    ]
